# Generated by Django 5.0.3 on 2024-04-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_product_description_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_colours',
            field=models.ManyToManyField(blank=True, null=True, to='cart.colourvariation'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.ManyToManyField(blank=True, null=True, to='cart.sizevariation'),
        ),
    ]
