# Generated by Django 5.0.3 on 2024-04-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_product_primary_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='secondary_categories',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
