# Generated by Django 5.0.3 on 2024-04-25 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_product_secondary_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_colours',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_sizes',
        ),
    ]
